<?xmlversion="1.0" encoding="UTF-8" standalone="yes"?>

<item>
<title>[COLOR yellow][B]  S.W.A.T - 1ª Temporada - Completa [/COLOR][/B][COLOR lime][B][/COLOR][/B]</title>
<link>http://ignorame</link>
<thumbnail>https://abutretorrents.com/capas/swat-1-temporada-completa-download-torrent-dublado-dual-audio-bluray-1080p-720p-4k-hd.jpg</thumbnail>
<fanart>https://mixdeseries.com.br/wp-content/uploads/2020/05/SWAT-sess%C3%A3o-globoplay.jpg</fanart>
<externallink>https://gitlab.com/flechanegra/seriesflashbrasil/-/raw/master/S.W.A.T_-_1%C2%AA_Temporada_-_Completa.txt</externallink>
<info> Um tenente do Esquadrão De Armas e Táticas Especiais recebe o comando de uma unidade de párias grosseiros, mas muito bem treinados. Sua equipe é chamada para resolver crimes de alta periculosidade sempre que todas as outras opções foram usadas. Secretamente, o tenente se sente em dúvida entre ser leal á corporação ou ás ruas das quais veio</item>
</item>

<item>
<title>[COLOR yellow][B]  S.W.A.T - 2ª Temporada - Completa [/COLOR][/B][COLOR lime][B][/COLOR][/B]</title>
<link>http://ignorame</link>
<thumbnail>https://1.bp.blogspot.com/-kvUMX7INhPM/W62HhI9NOzI/AAAAAAAAAzg/KpQxsU3VWOsgClSayjAXyMi3rQAj3qzaQCLcBGAs/s1600/Swat%2B2%2Btemporada%2Btorrent%2Bdownload%2Bdublada%2Bcompleta.jpg</thumbnail>
<fanart>https://mixdeseries.com.br/wp-content/uploads/2020/05/SWAT-sess%C3%A3o-globoplay.jpg</fanart>
<externallink>https://gitlab.com/flechanegra/seriesflashbrasil/-/raw/master/S.W.A_.T_-_2%C2%AA_Temporada_-_Completa.txt</externallink>
<info> Segunda temporada completa da série SWAT. O trabalho de uma unidade de elite da polícia da Califórnia, a Special Weapons And Tatics, encarregada de lidar com situações de alto risco, como assaltos com reféns, criminosos fortemente armados em locais abrigados, desativação de artefatos explosivos, psicopatas, ladrões de jóias, sequestros ou confrontos armados com gangues. Esse grupo seleto, altamente treinado e bem disciplinado, era formado por policiais voluntários, especialmente equipados e treinados para poderem reduzir o risco associado a uma situação de emergência. Emissora: ABC • Episódios: 25 • Duração: 44 min</item>
</item>

<item>
<title>[COLOR yellow][B]  S.W.A.T - 3ª Temporada - Completa [/COLOR][/B][COLOR lime][B][/COLOR][/B]</title>
<link>http://ignorame</link>
<thumbnail>https://abutretorrents.com/capas/swat-3-temporada-download-torrent-2017-dublado-dual-audio-bluray-1080p-720p-4k-hd.jpg</thumbnail>
<fanart>https://extra.globo.com/incoming/24403960-368-f5a/w444h250-PROP/swat-7.jpg</fanart>
<externallink>https://gitlab.com/flechanegra/seriesflashbrasil/-/raw/master/S.W.A_-T_-_3%C2%AA_Temporada-Completa.txt</externallink>
<info>Segue uma S.W.A.T nascida e criada localmente. sargento e sua equipe de homens e mulheres altamente treinados na solução de crimes em Los Angeles.</item>
</item>







