<?xmlversion="1.0" encoding="UTF-8" standalone="yes"?>

<item>
<title>[COLOR yellow][B]  S.W.A.T - 1ª Temporada - Completa [/COLOR][/B][COLOR lime][B][/COLOR][/B]</title>
<link>http://ignorame</link>
<thumbnail>https://abutretorrents.com/capas/swat-1-temporada-completa-download-torrent-dublado-dual-audio-bluray-1080p-720p-4k-hd.jpg</thumbnail>
<fanart>https://mixdeseries.com.br/wp-content/uploads/2020/05/SWAT-sess%C3%A3o-globoplay.jpg</fanart>
<externallink>https://gitlab.com/flechanegra/seriesflashbrasil/-/raw/master/S.W.A.T_-_1%C2%AA_Temporada_-_Completa.txt</externallink>
</item>



<item>
<title>[COLOR yellow][B]  S.W.A.T - 2ª Temporada - Completa [/COLOR][/B][COLOR lime][B][/COLOR][/B]</title>
<link>http://ignorame</link>
<thumbnail>https://1.bp.blogspot.com/-kvUMX7INhPM/W62HhI9NOzI/AAAAAAAAAzg/KpQxsU3VWOsgClSayjAXyMi3rQAj3qzaQCLcBGAs/s1600/Swat%2B2%2Btemporada%2Btorrent%2Bdownload%2Bdublada%2Bcompleta.jpg</thumbnail>
<fanart>https://mixdeseries.com.br/wp-content/uploads/2020/05/SWAT-sess%C3%A3o-globoplay.jpg</fanart>
<externallink>https://gitlab.com/flechanegra/seriesflashbrasil/-/raw/master/S.W.A_.T_-_2%C2%AA_Temporada_-_Completa.txt</externallink>
</item>




